using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Reflection;
using UnityEditor;
using UnityEngine;

namespace Elysia.Tables
{
    public static class CSVTableCodeGenerator
    {
        private static readonly string SCRIPT_TEMPLATE =
@"// <auto-generated>
//  automatically generated by CSVTableCodeGenerator, do not modify
// </auto-generated>

using System;
using System.Collections.Generic;
using UnityEngine;

namespace Elysia.Tables
{
    public class %%CLASS_NAME%%
    {
        public class Row
        {
[[VARIABLE]]

            public Row(CSVReader reader)
            {
[[VARIABLE_INITIALIZER]]
            }
        }

[[MEMBER_VARIABLE]]

        public int Count => _rows.Count;

        public void Load()
        {
            TextAsset textAsset = Resources.Load<TextAsset>(""Tables/%%FILE_NAME%%"");
            Load(textAsset);

            Resources.UnloadAsset(textAsset);
        }

        public void Load(TextAsset textAsset)
        {
            using CSVReader reader = new CSVReader(textAsset);
            reader.SkipLine();
            reader.SkipLine();

            int capacity = reader.GetLineCount();
[[MEMBER_INITIALIZE]]
            while (!reader.EndOfStream)
            {
[[LOAD_ROW]]
            }
        }

        public void Unload()
        {
            _rows = null;
        }

[[METHOD]]
    }
}
";

        public enum EVariableType
        {
            Unknown = -1,

            Primitive,
            String,
            Color,
            Color32,
            Vector3,
            Vector2,
            Enum,
            Custom,
        }

        public class Header
        {
            public string name;
            public string validatedName;
        }

        public class DataType
        {
            public string fieldTypeName;
            public string typeName;
            public EVariableType variableType;
            public EqualOperatorDelegate equalOperator;
            public bool isArray;

            public delegate string EqualOperatorDelegate();

            public static DataType Parse(string field)
            {
                DataType dataType = new DataType();
                if (string.IsNullOrEmpty(field))
                {
                    dataType.variableType = EVariableType.Unknown;
                    return dataType;
                }

                dataType.isArray = field.EndsWith("[]");

                string typeName = dataType.isArray ? field[..^2] : field;
                dataType.fieldTypeName = dataType.isArray ? $"IReadOnlyList<{typeName}>" : typeName;
                dataType.typeName = typeName;

                switch (typeName)
                {
                    case "bool":
                    case "byte":
                    case "sbyte":
                    case "char":
                    case "decimal":
                    case "double":
                    case "float":
                    case "int":
                    case "uint":
                    case "long":
                    case "ulong":
                    case "short":
                    case "ushort":
                        dataType.variableType = EVariableType.Primitive;
                        dataType.equalOperator = GetDefaultEqualOperator;
                        break;

                    case "string":
                        dataType.variableType = EVariableType.String;
                        dataType.equalOperator = GetDefaultEqualOperator;
                        break;

                    case "Color":
                        dataType.variableType = EVariableType.Color;
                        dataType.equalOperator = GetDefaultEqualOperator;
                        break;

                    case "Color32":
                        dataType.variableType = EVariableType.Color32;
                        dataType.equalOperator = GetColor32EqualOperator;
                        break;

                    case "Vector3":
                        dataType.variableType = EVariableType.Vector3;
                        dataType.equalOperator = GetDefaultEqualOperator;
                        break;

                    case "Vector2":
                        dataType.variableType = EVariableType.Vector2;
                        dataType.equalOperator = GetDefaultEqualOperator;
                        break;

                    default:
                        dataType.variableType = FindVariableType(typeName, out EqualOperatorDelegate equalOperator);
                        dataType.equalOperator = equalOperator;
                        break;
                }

                return dataType;
            }

            private static bool IsEnumType(string typeName)
            {
                foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
                {
                    Type t = assembly.GetType(typeName);
                    if (t != null && t.IsEnum)
                    {
                        return true;
                    }
                }

                return false;
            }

            private static EVariableType FindVariableType(string typeName, out EqualOperatorDelegate outEqualOperator)
            {
                if (IsEnumType(typeName))
                {
                    outEqualOperator = GetDefaultEqualOperator;
                    return EVariableType.Enum;
                }

                outEqualOperator = FindEqualOperatorDelegate(typeName);
                return EVariableType.Custom;
            }

            private static EqualOperatorDelegate FindEqualOperatorDelegate(string typeName)
            {
                Type t = typeof(Field);
                foreach (MethodInfo methodInfo in t.GetMethods(BindingFlags.Static | BindingFlags.Public))
                {
                    EqualOperatorAttribute equalOperatorAttribute = methodInfo.GetCustomAttribute<EqualOperatorAttribute>();
                    if (equalOperatorAttribute != null && equalOperatorAttribute.TypeName.Equals(typeName))
                    {
                        return methodInfo.CreateDelegate(typeof(EqualOperatorDelegate)) as EqualOperatorDelegate;
                    }
                }

                return GetDefaultEqualOperator;
            }
        }

        public class CSVData
        {
            public string FileName;
            public string ClassName;
            public Header[] Headers;
            public DataType[] Types;
            public bool UseDictionary;
            public int ColumnIdx;
        }

        private static readonly string SCRIPT_PATH = Application.dataPath + "/Scripts/Tables/";
        private static readonly string CSV_REGEX_PATTERN = ",(?=(?:[^\"]*\"[^\"]*\")*(?![^\"]*\"))";
        private static readonly Regex CSV_REGEX = new Regex(CSV_REGEX_PATTERN);

        private static readonly Dictionary<string, Action<StringBuilder, CSVData>> addFuncs = new Dictionary<string, Action<StringBuilder, CSVData>>()
        {
            { "[[VARIABLE]]",               AddVariable },
            { "[[VARIABLE_INITIALIZER]]",   AddVariableInitializer },
            { "[[MEMBER_VARIABLE]]",        AddMemberVariable },
            { "[[MEMBER_INITIALIZE]]",      AddMemberInitialize },
            { "[[LOAD_ROW]]",               AddLoadRow },
            { "[[METHOD]]",                 AddMethod },
        };

        [MenuItem("Assets/Create/C# Script from csv", false, 80)]
        public static void Generate()
        {
            if (Selection.objects == null || Selection.objects.Length == 0)
            {
                Debug.LogError($"[{nameof(CSVTableCodeGenerator)}] Select .csv file");
                return;
            }

            for (int i = 0; i < Selection.objects.Length; i++)
            {
                UnityEngine.Object obj = Selection.objects[i];

                string assetPath = AssetDatabase.GetAssetPath(obj);
                string extension = Path.GetExtension(assetPath).ToLower();
                if (!extension.Equals(".csv"))
                {
                    Debug.LogError($"[{nameof(CSVTableCodeGenerator)}] Select .csv file\nFile : {obj.name}");
                    continue;
                }

                CSVData csvData = LoadCSV(assetPath);
                if (csvData == null)
                {
                    Debug.LogError($"[{nameof(CSVTableCodeGenerator)}] csv load failed\nFile : {obj.name}");
                    continue;
                }

                try
                {
                    string str = GenerateScriptFromCSV(csvData);
                    SaveAs(str, $"{SCRIPT_PATH}{csvData.ClassName}.cs");
                }
                catch (Exception e)
                {
                    Debug.LogError($"[{nameof(CSVTableCodeGenerator)}] Generating codes failed\nFile : {obj.name}\n{e}");
                }
            }
        }

        private static CSVData LoadCSV(string path)
        {
            CSVData csvData = new CSVData();
            CodeDomProvider codeDomProvider = CodeDomProvider.CreateProvider("C#");

            csvData.FileName = Path.GetFileNameWithoutExtension(path);
            csvData.ClassName = ToPascalCase(csvData.FileName);

            StreamReader streamReader = new StreamReader(path);
            for (int lineIdx = 0, prevColumnCount = -1;; lineIdx++)
            {
                string line = streamReader.ReadLine();
                if (line == null)
                {
                    break;
                }

                string[] columns = CSV_REGEX.Split(line);
                if (prevColumnCount >= 0 && prevColumnCount != columns.Length)
                {
                    return null;
                }

                for (int i = 0; i < columns.Length; i++)
                {
                    columns[i] = columns[i].Replace("\"", "");
                }

                switch (lineIdx)
                {
                    case 0:
                        for (int i = 0; i < columns.Length; i++)
                        {
                            if (columns[i] != "@")
                            {
                                csvData.ColumnIdx = i;
                                break;
                            }
                        }

                        const string keySuffix = "_KEY";
                        if (columns[csvData.ColumnIdx].EndsWith(keySuffix))
                        {
                            columns[csvData.ColumnIdx] = columns[csvData.ColumnIdx].Remove(columns[csvData.ColumnIdx].Length - keySuffix.Length);
                            csvData.UseDictionary = true;
                        }

                        csvData.Headers = new Header[columns.Length];
                        for (int i = 0; i < csvData.Headers.Length; i++)
                        {
                            csvData.Headers[i] = new Header()
                            {
                                name = columns[i],
                                validatedName = codeDomProvider.IsValidIdentifier(columns[i]) ? columns[i] : $"@{columns[i]}",
                            };
                        }

                        break;

                    case 1:
                        DataType[] types = new DataType[columns.Length];
                        for (int i = 0; i < types.Length; i++)
                        {
                            types[i] = DataType.Parse(columns[i]);
                        }

                        csvData.Types = types;
                        break;
                }

                prevColumnCount = columns.Length;
            }

            return csvData;
        }

        private static string GenerateScriptFromCSV(CSVData csvData)
        {
            StringBuilder builder = new StringBuilder();

            string scripts = SCRIPT_TEMPLATE.
                             Replace("%%CLASS_NAME%%", csvData.ClassName).
                             Replace("%%REGEX%%", CSV_REGEX_PATTERN.Replace("\"", "\\\"")).
                             Replace("%%FILE_NAME%%", csvData.FileName);

            using StringReader reader = new StringReader(scripts);
            while (true)
            {
                string line = reader.ReadLine();
                if (line == null)
                {
                    break;
                }

                if (addFuncs.TryGetValue(line, out Action<StringBuilder, CSVData> del))
                {
                    del(builder, csvData);
                }
                else
                {
                    builder.AppendLine(line);
                }
            }

            return builder.ToString();
        }

        private static void AddVariable(StringBuilder builder, CSVData csvData)
        {
            string template = "            public %%TYPE%% %%NAME%% { get; private set; }";

            for (int i = csvData.ColumnIdx; i < csvData.Headers.Length; i++)
            {
                string line = template.
                    Replace("%%TYPE%%", csvData.Types[i].fieldTypeName).
                    Replace("%%NAME%%", csvData.Headers[i].validatedName);

                builder.AppendLine(line);
            }
        }

        private static void AddVariableInitializer(StringBuilder builder, CSVData csvData)
        {
            for (int i = 0; i < csvData.ColumnIdx; i++)
            {
                builder.AppendLine("                reader.SkipField();");
            }

            for (int i = csvData.ColumnIdx; i < csvData.Headers.Length; i++)
            {
                string line = $"                {csvData.Headers[i].validatedName} = reader.ReadField(){GetParseTemplate(csvData.Types[i])};";

                builder.AppendLine(line);
            }
        }

        private static void AddMemberVariable(StringBuilder builder, CSVData csvData)
        {
            string type = csvData.Types[csvData.ColumnIdx].fieldTypeName;

            string template = csvData.UseDictionary ?
@$"        private Dictionary<{type}, Row> _rows;
        public IReadOnlyDictionary<{type}, Row> Rows => _rows;" :

@$"        private List<Row> _rows;
        public IReadOnlyList<Row> Rows => _rows;";

            builder.AppendLine(template);
        }

        private static void AddMemberInitialize(StringBuilder builder, CSVData csvData)
        {
            string type = csvData.Types[csvData.ColumnIdx].fieldTypeName;

            string template = csvData.UseDictionary ?
@$"            _rows = new Dictionary<{type}, Row>(capacity);" :
@$"            _rows = new List<Row>(capacity);";

            builder.AppendLine(template);
        }

        private static void AddLoadRow(StringBuilder builder, CSVData csvData)
        {
            string type = csvData.Types[csvData.ColumnIdx].fieldTypeName;

            string template;
            if (csvData.UseDictionary)
            {
                template =
$@"                {type} key = reader.ReadField({csvData.ColumnIdx}){GetParseTemplate(csvData.Types[csvData.ColumnIdx])};
                reader.SeekCurrentLine();

                _rows.Add(key, new Row(reader));";
            }
            else
            {
                template = "                _rows.Add(new Row(reader));";
            }

            builder.AppendLine(template);
        }

        private static void AddMethod(StringBuilder builder, CSVData csvData)
        {
            string indexerTemplate =
@"        public Row this[%%TYPE%% key] => _rows[key];";

            string getTemplate =
@"        public bool ContainsKey(%%TYPE%% key) => _rows.ContainsKey(key);

        public bool TryGetValue(%%TYPE%% key, out Row row) => _rows.TryGetValue(key, out row);";

            string findTemplate =
@"        public Row Find%%NAME%%(%%TYPE%% key)
        {
            for (int i = 0; i < _rows.Count; i++)
            {
                Row row = _rows[i];
                if (%%EQUAL_OPERATOR%%)
                {
                    return row;
                }
            }

            return null;
        }";

            string findAllTemplate =
@"        public List<Row> Find%%NAME%%All(%%TYPE%% key)
        {
            List<Row> result = new List<Row>(_rows.Count);
            Find%%NAME%%All(key, result);

            return result;
        }

        public void Find%%NAME%%All(%%TYPE%% key, List<Row> result)
        {
            for (int i = 0; i < _rows.Count; i++)
            {
                Row row = _rows[i];
                if (%%EQUAL_OPERATOR%%)
                {
                    result.Add(row);
                }
            }
        }";

            if (csvData.UseDictionary)
            {
                string indexerLine = indexerTemplate.Replace("%%TYPE%%", csvData.Types[csvData.ColumnIdx].fieldTypeName);
                builder.AppendLine(indexerLine);
                builder.AppendLine();

                string getLine = getTemplate.Replace("%%TYPE%%", csvData.Types[csvData.ColumnIdx].fieldTypeName);
                builder.AppendLine(getLine);
            }
            else
            {
                string indexerLine = indexerTemplate.Replace("%%TYPE%%", "int");
                builder.AppendLine(indexerLine);
                builder.AppendLine();

                for (int i = csvData.ColumnIdx; i < csvData.Headers.Length; i++)
                {
                    DataType dataType = csvData.Types[i];
                    if (dataType.isArray)
                    {
                        continue;
                    }


                    if (i > csvData.ColumnIdx)
                    {
                        builder.AppendLine();
                    }

                    string equalOperatorTemplate = dataType.equalOperator();
                    string equalLine = equalOperatorTemplate.
                        Replace("%%LHS%%", "row.%%VALID_NAME%%").
                        Replace("%%RHS%%", "key");

                    string findLine = findTemplate.
                        Replace("%%EQUAL_OPERATOR%%", equalLine).
                        Replace("%%NAME%%", csvData.Headers[i].name).
                        Replace("%%VALID_NAME%%", csvData.Headers[i].validatedName).
                        Replace("%%TYPE%%", csvData.Types[i].fieldTypeName);
                    builder.AppendLine(findLine);
                    builder.AppendLine();

                    string findAllLine = findAllTemplate.
                        Replace("%%EQUAL_OPERATOR%%", equalLine).
                        Replace("%%NAME%%", csvData.Headers[i].name).
                        Replace("%%VALID_NAME%%", csvData.Headers[i].validatedName).
                        Replace("%%TYPE%%", csvData.Types[i].fieldTypeName);
                    builder.AppendLine(findAllLine);
                }
            }
        }

        private static void SaveAs(string str, string filePath)
        {
            try
            {
                using StreamWriter writer = File.CreateText(filePath);
                writer.Write(str);

                Debug.Log($"[{nameof(CSVTableCodeGenerator)}] Script saved : {filePath}");
            }
            catch (Exception e)
            {
                Debug.LogError($"[{nameof(CSVTableCodeGenerator)}] {e}");
            }
            finally
            {
                AssetDatabase.Refresh();
            }
        }

        private static string GetParseTemplate(DataType dataType)
        {
            if (dataType.isArray)
            {
                if (dataType.variableType == EVariableType.Enum)
                {
                     return $".ToArray(e => e.ToEnum<{dataType.typeName}>())";
                }

                return $".ToArray(e => ({dataType.typeName})e)";
            }

            return dataType.variableType == EVariableType.Enum ? $".ToEnum<{dataType.typeName}>()" : "";
        }

        private static string ToPascalCase(string original)
        {
            Regex invalidCharsRgx = new Regex("[^_a-zA-Z0-9]");
            Regex whiteSpace = new Regex(@"(?<=\s)");
            Regex startsWithLowerCaseChar = new Regex("^[a-z]");
            Regex firstCharFollowedByUpperCasesOnly = new Regex("(?<=[A-Z])[A-Z0-9]+$");
            Regex lowerCaseNextToNumber = new Regex("(?<=[0-9])[a-z]");
            Regex upperCaseInside = new Regex("(?<=[A-Z])[A-Z]+?((?=[A-Z][a-z])|(?=[0-9]))");

            // replace white spaces with undescore, then replace all invalid chars with empty string
            var pascalCase = invalidCharsRgx.Replace(whiteSpace.Replace(original, "_"), string.Empty)
                // split by underscores
                .Split(new char[] { '_' }, StringSplitOptions.RemoveEmptyEntries)
                // set first letter to uppercase
                .Select(w => startsWithLowerCaseChar.Replace(w, m => m.Value.ToUpper()))
                // replace second and all following upper case letters to lower if there is no next lower (ABC -> Abc)
                .Select(w => firstCharFollowedByUpperCasesOnly.Replace(w, m => m.Value.ToLower()))
                // set upper case the first lower case following a number (Ab9cd -> Ab9Cd)
                .Select(w => lowerCaseNextToNumber.Replace(w, m => m.Value.ToUpper()))
                // lower second and next upper case letters except the last if it follows by any lower (ABcDEf -> AbcDef)
                .Select(w => upperCaseInside.Replace(w, m => m.Value.ToLower()));

            return string.Concat(pascalCase);
        }

        public static string GetColor32EqualOperator()
        {
            return @"%%LHS%%.r == %%RHS%%.r && %%LHS%%.g == %%RHS%%.g && %%LHS%%.b == %%RHS%%.b && %%LHS%%.a == %%RHS%%.a";
        }

        public static string GetDefaultEqualOperator()
        {
            return @"%%LHS%% == %%RHS%%";
        }
    }
}
