using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEngine;
using UnityEditor;

namespace Elysia.GoogleSheets
{
    public class GoogleSheetsCodeGenerator : EditorWindow
    {
        private enum ETableType
        {
            List,
            Dictionary,
        }

        private class Table
        {
            public string Id { get; }
            public string Range { get; }
            public string ClassName { get; }
            public ETableType Type { get; }
            public string KeyName { get; }

            public IReadOnlyList<GoogleSheetsReader.Header> Headers { get; private set; }
            public GoogleSheetsReader.Header Key { get; private set; }

            public Table(string id, string range, string className, ETableType tableType, string keyName)
            {
                Id = id;
                Range = range;
                ClassName = className;
                Type = tableType;
                KeyName = keyName;
            }

            public string GetScript()
            {
                StringBuilder builder = new StringBuilder();

                {
                    GoogleSheetsReader reader = new GoogleSheetsReader(Id, Range, 3);
                    reader.Load();
                    Headers = reader.GetHeaders();
                    Key = Headers.FirstOrDefault(e => e.FieldName == KeyName);
                }

                {
                    using StringReader reader = new StringReader(SCRIPT_TEMPLATE);
                    while (true)
                    {
                        string line = reader.ReadLine();
                        if (line == null)
                        {
                            break;
                        }

                        if (AddFunc.TryGetValue(line, out Action<StringBuilder, Table> del))
                        {
                            del(builder, this);
                        }
                        else
                        {
                            builder.AppendLine(line);
                        }
                    }
                }

                return builder.Replace("%%SHEET_ID%%", Id)
                              .Replace("%%SHEET_RANGE%%", Range)
                              .Replace("%%CLASS_NAME%%", ClassName)
                              .Replace("%%TABLE_TYPE%%", Type.ToString())
                              .Replace("%%TABLE_KEY_NAME%%", KeyName)
                              .ToString();
            }
        }

        private string _sheetId;
        private string _sheetRange;
        private string _className;
        private ETableType _tableType;
        private string _tableKeyName;

        private static readonly string SUB_DIRECTORY = "Scripts/Tables";
        private static readonly string SCRIPT_DIRECTORY = Path.Combine(Application.dataPath, SUB_DIRECTORY);
        private static readonly string KEY_SHEET_ID = $"{nameof(GoogleSheetsCodeGenerator)}/sheet_id";
        private static readonly string KEY_SHEET_RANGE = $"{nameof(GoogleSheetsCodeGenerator)}/sheet_range";
        private static readonly string KEY_CLASS_NAME = $"{nameof(GoogleSheetsCodeGenerator)}/class_name";
        private static readonly string KEY_TABLE_TYPE = $"{nameof(GoogleSheetsCodeGenerator)}/table_type";
        private static readonly string KEY_TABLE_KEY_NAME = $"{nameof(GoogleSheetsCodeGenerator)}/table_key_name";
        private static readonly Regex REGEX = new Regex(@"\/\*\s*meta([\s\S]*?)\*\/", RegexOptions.Multiline);

        private static readonly Dictionary<string, Action<StringBuilder, Table>> AddFunc = new Dictionary<string, Action<StringBuilder, Table>>()
        {
            { "[[VARIABLE]]",               AddVariable },
            { "[[VARIABLE_INITIALIZER]]",   AddVariableInitializer },
            { "[[MEMBER_VARIABLE]]",        AddMemberVariable },
            { "[[MEMBER_INITIALIZE]]",      AddMemberInitialize },
            { "[[METHOD]]",                 AddMethod },
        };

        private static readonly string SCRIPT_TEMPLATE =
@"// <auto-generated>
//  automatically generated by GoogleSheetsCodeGenerator, do not modify
// </auto-generated>

/* meta
%%CLASS_NAME%%
%%SHEET_ID%%
%%SHEET_RANGE%%
%%TABLE_TYPE%%
%%TABLE_KEY_NAME%%
*/

using System.Collections.Generic;
using System.Threading.Tasks;
using Elysia.GoogleSheets;

namespace Elysia.Tables
{
    public class %%CLASS_NAME%%
    {
        public class Row
        {
[[VARIABLE]]

            public Row(GoogleSheetsRow row, GoogleSheetsRow defaultValue)
            {
[[VARIABLE_INITIALIZER]]
            }
        }

[[MEMBER_VARIABLE]]

        public int Count => _rows.Count;

        private static readonly string _id = ""%%SHEET_ID%%"";
        private static readonly string _range = ""%%SHEET_RANGE%%"";

        public void Load()
        {
            GoogleSheetsReader reader = new GoogleSheetsReader(_id, _range, 3);
            reader.Load();

            GoogleSheetsRow defaultValues = reader.GetDefaultValues();

            int lineCount = reader.LineCount;
[[MEMBER_INITIALIZE]]

            OnLoaded();
        }

        public async Task LoadAsync()
        {
            GoogleSheetsReader reader = new GoogleSheetsReader(_id, _range, 3);
            await reader.LoadAsync();

            GoogleSheetsRow defaultValues = reader.GetDefaultValues();

            int lineCount = reader.LineCount;
[[MEMBER_INITIALIZE]]

            OnLoaded();
        }

        public void Unload()
        {
            _rows = null;
            OnUnLoaded();
        }

[[METHOD]]

        protected virtual void OnLoaded()
        {
        }

        protected virtual void OnUnLoaded()
        {
        }
    }
}
";

        [MenuItem("Google Sheets/Code Generator")]
        public static void ShowWindow()
        {
            if (!Directory.Exists(SCRIPT_DIRECTORY))
            {
                Directory.CreateDirectory(SCRIPT_DIRECTORY);
                AssetDatabase.Refresh();
            }

            GoogleSheetsCodeGenerator window = GetWindow<GoogleSheetsCodeGenerator>();
            window.LoadPrefs();
        }

        private void LoadPrefs()
        {
            _sheetId = EditorPrefs.GetString(KEY_SHEET_ID, "");
            _sheetRange = EditorPrefs.GetString(KEY_SHEET_RANGE, "");
            _className = EditorPrefs.GetString(KEY_CLASS_NAME, "");
            if (Enum.TryParse(EditorPrefs.GetString(KEY_TABLE_TYPE, ""), out ETableType t))
            {
                _tableType = t;
            }
            _tableKeyName = EditorPrefs.GetString(KEY_TABLE_KEY_NAME, "");
        }

        private void SavePrefs()
        {
            EditorPrefs.SetString(KEY_SHEET_ID, _sheetId);
            EditorPrefs.SetString(KEY_SHEET_RANGE, _sheetRange);
            EditorPrefs.SetString(KEY_CLASS_NAME, _className);
            EditorPrefs.SetString(KEY_TABLE_TYPE, _tableType.ToString());
            EditorPrefs.SetString(KEY_TABLE_KEY_NAME, _tableKeyName);
        }

        private void OnGUI()
        {
            {
                using EditorGUI.ChangeCheckScope scope = new EditorGUI.ChangeCheckScope();

                {
                    using var _ = new EditorGUILayout.HorizontalScope();
                    _sheetId = EditorGUILayout.TextField("Sheet ID", _sheetId);

                    if (GUILayout.Button("Open", GUILayout.Width(80)))
                    {
                        Application.OpenURL($"https://docs.google.com/spreadsheets/d/{_sheetId}");
                    }
                }
                _sheetRange = EditorGUILayout.TextField("Range", _sheetRange);
                _className = EditorGUILayout.TextField("Class Name", _className);
                _tableType = (ETableType)EditorGUILayout.EnumPopup("Table Type", _tableType);

                {
                    using var _ = new EditorGUI.DisabledScope(_tableType != ETableType.Dictionary);

                    _tableKeyName = EditorGUILayout.TextField("Key Field Name", _tableKeyName);
                }

                if (scope.changed)
                {
                    SavePrefs();
                }
            }

            if (GUILayout.Button("Load configs from exist file"))
            {
                GUI.FocusControl(null);
                string path = EditorUtility.OpenFilePanel("Select exist script...", SCRIPT_DIRECTORY, "cs");

                try
                {
                    string script = File.ReadAllText(path);

                    Match match = REGEX.Match(script);
                    string[] lines = match.Groups[1].Value.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);

                    string className = lines[1];
                    string id = lines[2];
                    string range = lines[3];
                    ETableType tableType = Enum.Parse<ETableType>(lines[4]);
                    string tableKeyName = lines[5];

                    _sheetId = id;
                    _sheetRange = range;
                    _className = className;
                    _tableType = tableType;
                    _tableKeyName = tableKeyName;

                    SavePrefs();
                }
                catch (Exception e)
                {
                    Debug.LogError($"[{nameof(GoogleSheetsCodeGenerator)}] {e}");
                }
            }

            EditorGUILayout.Space(10f);
            if (GUILayout.Button("Generate"))
            {
                Table table = new Table(_sheetId, _sheetRange, _className, _tableType, _tableKeyName);
                GenerateScript(table);
            }
        }

        private static void GenerateScript(Table table)
        {
            string scripts = table.GetScript();

            try
            {
                string fileName = $"{table.ClassName}.cs";
                string filePath = Path.Combine(SCRIPT_DIRECTORY, fileName);

                {
                    using StreamWriter writer = File.CreateText(filePath);
                    writer.Write(scripts);
                }

                AssetDatabase.Refresh();

                UnityEngine.Object asset = AssetDatabase.LoadAssetAtPath(Path.Combine("Assets", SUB_DIRECTORY, fileName), typeof(TextAsset));
                Debug.Log($"[{nameof(GoogleSheetsCodeGenerator)}] Script saved : {filePath}", asset);
            }
            catch (Exception e)
            {
                Debug.LogError($"[{nameof(GoogleSheetsCodeGenerator)}] {e}");
            }
        }

        private static void AddVariable(StringBuilder builder, Table table)
        {
            string template = "            public %%TYPE%% %%NAME%% { get; }";

            IReadOnlyList<GoogleSheetsReader.Header> headers = table.Headers;
            for (int i = 0; i < headers.Count; i++)
            {
                GoogleSheetsReader.Header header = headers[i];

                if (header.IsComment)
                {
                    continue;
                }

                string line = template.
                              Replace("%%TYPE%%", header.FieldTypeName).
                              Replace("%%NAME%%", header.ValidatedFieldName);

                builder.AppendLine(line);
            }
        }

        private static void AddVariableInitializer(StringBuilder builder, Table table)
        {
            IReadOnlyList<GoogleSheetsReader.Header> headers = table.Headers;
            for (int i = 0; i < headers.Count; i++)
            {
                GoogleSheetsReader.Header header = headers[i];

                if (header.IsComment)
                {
                    string line = "                row.SkipField();";
                    builder.AppendLine(line);
                }
                else
                {
                    string line = $"                {header.ValidatedFieldName} = row.ReadField(defaultValue[row.Position]){GetParseTemplate(header)};";
                    builder.AppendLine(line);
                }
            }
        }

        private static string GetParseTemplate(GoogleSheetsReader.Header header)
        {
            if (header.IsArray)
            {
                if (header.VariableType == EVariableType.Enum)
                {
                    return $".ToArray(e => e.ToEnum<{header.BaseType}>())";
                }

                return $".ToArray(e => ({header.BaseType})e)";
            }

            return header.VariableType == EVariableType.Enum ? $".ToEnum<{header.BaseType}>()" : "";
        }

        private static void AddMemberVariable(StringBuilder builder, Table table)
        {
            if (table.Type == ETableType.Dictionary)
            {
                string type = table.Key.BaseType;

                string template =
@$"        private Dictionary<{type}, Row> _rows;
        public IReadOnlyDictionary<{type}, Row> Rows => _rows;";

                builder.AppendLine(template);
            }
            else
            {
                string template =
@$"        private List<Row> _rows;
        public IReadOnlyList<Row> Rows => _rows;";

                builder.AppendLine(template);
            }
        }

        private static void AddMemberInitialize(StringBuilder builder, Table table)
        {
            if (table.Type == ETableType.Dictionary)
            {
                string type = table.Key.BaseType;
                int keyIndex = table.Key.Index;
                GoogleSheetsReader.Header header = table.Headers[keyIndex];
                string template =
$@"            _rows = new Dictionary<{type}, Row>(lineCount);
            for (int i = 0; i < lineCount; i++)
            {{
                GoogleSheetsRow line = reader.ReadLine();
                _rows.Add(line.ReadField({keyIndex}, defaultValues[{keyIndex}]){GetParseTemplate(header)}, new Row(line, defaultValues));
            }}";
                builder.AppendLine(template);
            }
            else
            {
                GoogleSheetsReader.Header header = table.Headers[0];
                string template =
@$"            _rows = new List<Row>(lineCount);
            for (int i = 0; i < lineCount; i++)
            {{
                _rows.Add(new Row(line.ReadField(defaultValues[0]){GetParseTemplate(header)}, defaultValues));
            }}";
                builder.AppendLine(template);
            }
        }

        private static void AddMethod(StringBuilder builder, Table table)
        {
            string indexerTemplate =
@"        public Row this[%%TYPE%% key] => _rows[key];";

            string getTemplate =
@"        public bool ContainsKey(%%TYPE%% key) => _rows.ContainsKey(key);

        public bool TryGetValue(%%TYPE%% key, out Row row) => _rows.TryGetValue(key, out row);";

            if (table.Type == ETableType.Dictionary)
            {
                string indexerLine = indexerTemplate.Replace("%%TYPE%%", table.Key.FieldTypeName);
                builder.AppendLine(indexerLine);
                builder.AppendLine();

                string getLine = getTemplate.Replace("%%TYPE%%", table.Key.FieldTypeName);
                builder.AppendLine(getLine);
            }
            else
            {
                string indexerLine = indexerTemplate.Replace("%%TYPE%%", "int");
                builder.AppendLine(indexerLine);
            }
        }
    }
}
